epochs: 100000
iters_per_checkpoint: 10000  # Change in fine tuning mode
stop_iteration: 185000
seed: 1234
dynamic_loss_scaling: True
fp16_run: False
distributed_run: False
dist_backend: "nccl"
dist_url: "tcp://localhost:54321"
cudnn_enabled: True
cudnn_benchmark: False
ignore_layers: ['embedding.weight']

################################
# Data Parameters             #
################################
dataset_path: "/home/aiteam/Documents/LibriTTS-clean_preprocessed"

################################
# Audio Parameters             #
################################
max_wav_value: 32768.0
sampling_rate: 22050
filter_length: 1024
hop_length: 256
win_length: 1024
n_mel_channels: 80
mel_fmin: 0.0
mel_fmax: 8000.0
mel_token_value: -11.5129

################################
# Model Parameters             #
################################
symbols_embedding_dim: 512
speaker_embedding_dim: 256

# Encoder parameters
encoder_kernel_size: 5
encoder_n_convolutions: 3
encoder_embedding_dim: 512

# Duration predictor parameters
duration_rnn_dim: 512
duration_rnn_num_layers: 2

# Range Predictor parameters
range_model_input_size: 769 # 512 + 256 + 1
range_rnn_dim: 512
range_rnn_num_layers: 2

# Positional Encoding Parameters
positional_encoding_d: 32
positional_encoding_max_len: 500

# Decoder parameters
n_frames_per_step: 1  # currently only 1 is supported
decoder_rnn_dim: 1024
prenet_dim: 256
prenet_f0_n_layers: 1
prenet_f0_dim: 1
prenet_f0_kernel_size: 1

max_decoder_steps: 1000
p_attention_dropout: 0.1
p_decoder_dropout: 0.1

# Attention parameters
attention_rnn_dim: 1024
attention_dim: 128

# Mel-post processing network parameters
postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 4

################################
# Optimization Hyperparameters #
################################
use_saved_learning_rate: False
learning_rate: 0.0003 # 3e-5
weight_decay: 0.000001 # 1e-6
grad_clip_thresh: 1.0
batch_size: 32
mask_padding: True  # set model's padded outputs to padded values
